### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KuhakuPixel** [KuhakuPixel/AceTheGame#60]
## APK

- [ ] Fix Progress bar not working, when using non rooted method
- [ ] Add options to write value to all address in address table

- [ ] More descriptive name for `Scan Type`

> like cheat engine, where the name of scan type
> is `Exact Scan`, `Less than` and etc are more readable
> than symbols `=`, `<`

- [ ] Option to add address manually to address table

- [ ] Option to add all matches to address table

- [ ] Option to Pause while scanning

- [x] Freeze value of an address

- [ ] show value of an address in real time 

- [ ] Undo
> add an option to limit matches count
> that can be undo-ed so it won't consume
> too much memory

- [ ] Debugger

## ACE
- [ ] Use data-format like json for communication to APK

> currently messages sent by `ACE` to APK are hard to read because it only sent the "raw" message like when giving request, its hard to know
> if the request is a success or failure
